[build]
  publish = ".next"
  command = "npm ci && npm run build"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "20.18.0"
  NODE_ENV = "production"
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_OPTIONS = "--max-old-space-size=4096"

# Functions configuration
[functions]
  external_node_modules = ["axios"]
  node_bundler = "esbuild"

# Remove Next.js plugin to avoid conflicts
# [[plugins]]
#   package = "@netlify/plugin-nextjs"

# Headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"

# API Routes to Netlify Functions
[[redirects]]
  from = "/api/realtime-prices"
  to = "/.netlify/functions/realtime-prices"
  status = 200
  force = true

[[redirects]]
  from = "/api/coinmarketcap"
  to = "/.netlify/functions/coinmarketcap-data"
  status = 200
  force = true

[[redirects]]
  from = "/api/hiro"
  to = "/.netlify/functions/hiro-data"
  status = 200
  force = true

[[redirects]]
  from = "/api/bitcoin-price"
  to = "/.netlify/functions/bitcoin-price"
  status = 200
  force = true

[[redirects]]
  from = "/api/runes-list"
  to = "/.netlify/functions/runes-list"
  status = 200
  force = true

[[redirects]]
  from = "/api/arbitrage/opportunities"
  to = "/.netlify/functions/arbitrage-opportunities"
  status = 200
  force = true

[[redirects]]
  from = "/api/runes/*"
  to = "/.netlify/functions/runes-data"
  status = 200
  force = true

[[redirects]]
  from = "/api/ordinals/*"
  to = "/.netlify/functions/ordinals-data"
  status = 200
  force = true

# External API Proxies for CORS handling
[[redirects]]
  from = "/api/mempool-direct/*"
  to = "https://mempool.space/api/:splat"
  status = 200
  force = true
  headers = {X-From = "Netlify"}

[[redirects]]
  from = "/api/coingecko-direct/*"
  to = "https://api.coingecko.com/api/v3/:splat"
  status = 200
  force = true
  headers = {X-From = "Netlify"}

# SPA fallback - must be last
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Cache optimization
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

# Environment variables for build
[context.production.environment]
  NODE_ENV = "production"
  NEXT_TELEMETRY_DISABLED = "1"

[context.deploy-preview.environment]
  NODE_ENV = "production"
  NEXT_TELEMETRY_DISABLED = "1"

[context.branch-deploy.environment]
  NODE_ENV = "production"
  NEXT_TELEMETRY_DISABLED = "1"