services:
  - type: web
    name: cypher-ordi-future
    env: node
    plan: starter
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_API_URL
        value: https://api.ordiscan.com/v1/
      - key: NEXT_PUBLIC_APP_URL
        sync: false
      - key: NODE_VERSION
        value: 18.17.0
    autoDeploy: true
    disk:
      name: tmp
      mountPath: /tmp
      sizeGB: 1
    scaling:
      minInstances: 1
      maxInstances: 1
      targetMemoryPercent: 80
      targetCPUPercent: 80 