services:
  - type: web
    name: cypher-ordi-future
    env: node
    plan: starter
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_API_URL
        value: https://api.ordiscan.com/v1/
      - key: NEXT_PUBLIC_APP_URL
        sync: false
      - key: NODE_VERSION
        value: 18.17.0
      - key: NEXT_PUBLIC_COINMARKETCAP_API_KEY
        value: c045d2a9-6f2d-44e9-8297-a88ab83b463b
      - key: NEXT_PUBLIC_ORDISCAN_API_KEY
        value: e227a764-b31b-43cf-a60c-be5daa50cd2c
      - key: NEXT_PUBLIC_SUPABASE_URL
        value: https://your-supabase-project.supabase.co
      - key: NEXT_PUBLIC_SUPABASE_ANON_KEY
        value: your-supabase-anon-key
    autoDeploy: true
    branch: upgrade-2.5X
    disk:
      name: tmp
      mountPath: /tmp
      sizeGB: 1
    scaling:
      minInstances: 1
      maxInstances: 1
      targetMemoryPercent: 80
      targetCPUPercent: 80