name: CI

on:
  push:
    branches: [ main, upgrade-2.5X ]
  pull_request:
    branches: [ main, upgrade-2.5X ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - name: Notify Render
      if: success() && github.event_name == 'push'
      run: |
        curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK_URL }} -H "Content-Type: application/json" -d '{"branch":"${{ github.ref_name }}"}'
